[build]
  command = "hugo -F"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.121.2"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"